package by.htp.les.controller.command;

public enum CommandName {
LOGINATION,REGISTRATION,SAVENEWUSER, GOTOINDEXPAGE,GOTOMAINPAGE,LOGOUT,READNEWS,UPDATENEWS,SAVENEWS,DELETENEWS,ADDNEWS, GOTOADDNEWSPAGE,LOCALIZATION
}
